### ISSUE TITLE
license is missing some information

### ISSUE THREAD

**Issue by JakeChampion** [tidal-music/aws-fastly-http-client#1]
Hi, I was checking through this project and it looks great, I however did notice the license is missing a year and named copyright owner - I think those would need to be added so that other projects can attribute this code with the correct owner

https://github.com/tidal-music/aws-fastly-http-client/blob/main/LICENSE#L195

>   Copyright [yyyy] [name of copyright owner]

**Comment by tidal-gaute** [comment]
Oops, my bad! I updated the license.

Thanks for your feedback!
